import { Run, Step } from "./api";

export function exportRunToMarkdown(run: Run, steps: Step[]): string {
  let md = `# Agent Run: ${run.name}\n\n`;
  
  md += `**Run ID:** \`${run.id}\`  \n`;
  md += `**Status:** ${run.status}  \n`;
  md += `**Model:** ${run.model || "N/A"}  \n`;
  md += `**Created:** ${new Date(run.created_at).toLocaleString()}  \n`;
  md += `**Duration:** ${formatDuration(run.created_at, run.updated_at)}  \n`;
  
  if (run.tags && run.tags.length > 0) {
    md += `**Tags:** ${run.tags.map(t => `\`${t}\``).join(", ")}  \n`;
  }
  
  md += `\n---\n\n## Timeline\n\n`;
  
  const startTime = new Date(run.created_at).getTime();
  
  steps.forEach((step, index) => {
    const relativeTime = (new Date(step.timestamp).getTime() - startTime) / 1000;
    md += `### Step ${index + 1}: ${step.type} (+${relativeTime.toFixed(2)}s)\n`;
    
    if (step.duration) {
      md += `*Duration: ${step.duration}ms*\n\n`;
    } else {
      md += `\n`;
    }
    
    if (step.type === "LLM_CALL" && step.payload) {
      md += `#### Prompt\n\`\`\`json\n${JSON.stringify(step.payload.prompt, null, 2)}\n\`\`\`\n\n`;
      md += `#### Response\n\`\`\`json\n${JSON.stringify(step.payload.response, null, 2)}\n\`\`\`\n\n`;
    } else if (step.type === "TOOL_CALL" && step.payload) {
      md += `**Tool:** \`${step.payload.name}\`\n\n`;
      md += `#### Arguments\n\`\`\`json\n${JSON.stringify(step.payload.args, null, 2)}\n\`\`\`\n\n`;
      md += `#### Result\n\`\`\`json\n${JSON.stringify(step.payload.result, null, 2)}\n\`\`\`\n\n`;
    } else {
      md += `\`\`\`json\n${JSON.stringify(step.payload, null, 2)}\n\`\`\`\n\n`;
    }
    
    md += `---\n\n`;
  });
  
  md += `*Generated by Agent Flight Recorder*\n`;
  
  return md;
}

function formatDuration(created: string, updated: string): string {
  const ms = new Date(updated).getTime() - new Date(created).getTime();
  if (ms < 1000) return `${ms}ms`;
  if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
  return `${(ms / 60000).toFixed(1)}m`;
}

export function downloadFile(content: string, fileName: string, contentType: string) {
  const a = document.createElement("a");
  const file = new Blob([content], { type: contentType });
  a.href = URL.createObjectURL(file);
  a.download = fileName;
  a.click();
  URL.revokeObjectURL(a.href);
}
